### ISSUE TITLE
0.11 Crashes

### ISSUE THREAD

**Issue by recrudesce** [UncleGoogle/galaxy-integration-humblebundle#191]
**Describe the bug**
0.10 and 0.11 crash in 2.0.54.24 Beta GOG Galaxy

**Expected behavior**
I mean, it should work, right ?

**Plugin installed**
Manually installed from github releases, have tried both 0.10 and 0.11 releases.  Unzipped to the plugins/installed folder.

**Provide logs**
No plugin specific log files are created, the only thing is in the GalaxyClient log, which says the following:

```
2022-09-27 13:47:20.994 [Information][ (0)] [TID 65676][galaxy_client]: Plugin pluginID/humble_f0ca3d80-a432-4d35-a9e3-60f27161ac3a stopped, previous state Initializing
2022-09-27 13:47:20.994 [Error][ (0)] [TID 65676][galaxy_client]: Plugin - pluginID/humble_f0ca3d80-a432-4d35-a9e3-60f27161ac3a has crashed.
2022-09-27 13:47:20.994 [Information][ (0)] [TID 65676][galaxy_client]: Not sending problem report as the user has disabled it.
2022-09-27 13:47:20.996 [Information][ (0)] [TID 65676][galaxy_client]: Scheduling problem report 'plug-in_crashed_report' (type 'external_integrations_failed').
```

I've deleted the webcache, the db file, and the plugin, done a clean install of the plugin, and still it crashes with no log file created.
I also named the folder `humble_f0ca3d80-a432-4d35-a9e3-60f27161ac3a` to see if that made any difference, but it did not.

The plugin from the Integrations search works fine, but it's several versions out of date and doesn't have the Game Choice/Collection features that I'm after.

**Comment by UncleGoogle** [comment]
Hi, what is your OS? Could you please follow this instruction? https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/155#issuecomment-800666512 and paste the result? Maybe it is the same problem

**Comment by recrudesce** [comment]
Win 11, and exactly the same error as #155 

```
C:\Users\recrudesce\AppData\Local\GOG.com\Galaxy\plugins\installed\humble>"C:\Program Files (x86)\GOG Galaxy\python\python.exe" -c "import sys; sys.path.append('.'); import plugin; plugin.main()"

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\recrudesce\AppData\Local\GOG.com\Galaxy\plugins\installed\humble\modules\Python.Runtime.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at clrModule.PyInit_clr()
```

**Comment by recrudesce** [comment]
FIX: Go to ` %LocalAppData%\GOG.com\Galaxy\plugins\installed\humble-...\modules`, find the `Python.Runtime.dll` file, right click and choose Properties.  At the bottom, tick the "Unblock" tickbox, click OK.

Works absolutely fine after that.
